### ISSUE TITLE
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

### ISSUE THREAD

**Issue by Fkhaibari** [pancakeswap/token-list#125]
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

_Originally posted by @akshay-rakheja in https://github.com/ethereum/EIPs/pull/6498_

**Comment by theharv3st** [comment]
What are you talking about I'm new I need support I got so much CAKE coming in. My dog recently passed away and seeing the DOG NFT lead me to this. Have a heart. Not everybody is a scamm3r. 

RIP Maya 🐕

**Comment by xinbenlv** [comment]
Yeah, this is a spam. @Pandapip1

**Comment by Pandapip1** [comment]
Apparently this is a bot magnet :/
