### ISSUE TITLE
Add USD+ to token list #174

### ISSUE THREAD

**Issue by maximlafe** [pancakeswap/token-list#50]
"chainId": 56,
"address": "0x73cb180bf0521828d8849bc8CF2B920918e23032",
"decimals": 18,
"name": "USD+",
"symbol": "USD+",
"logoURI": "https://2173993027-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F9HhCCgYexXiRot0OWAJY%2Fuploads%2FHCzDW3p9ZkqGuC42prEh%2FUSD%2B_NEW.png?alt=media&token=5700174c-1ad1-4726-bc9f-94abe8dac1d2",
"extensions": {},

**Comment by maximlafe** [comment]
any updates here?

**Comment by Fkhaibari** [comment]
> "chainId": 56,
> 
> "address": "0x3597750ccec61910cf42a66Cd755b58695e6B858",
> 
> "decimals": 18,
> 
> "name": "USD+",
> 
> "symbol": "USD+",
> 
> "logoURI": "https://2173993027-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F9HhCCgYexXiRot0OWAJY%2Fuploads%2FHCzDW3p9ZkqGuC42prEh%2FUSD%2B_NEW.png?alt=media&token=5700174c-1ad1-4726-bc9f-94abe8dac1d2",
> 
> "extensions": {},

**Comment by ChefJerry** [comment]
sorry, the address `0x73cb180bf0521828d8849bc8CF2B920918e23032` is not a valid ERC20 token
