### ISSUE TITLE
Can't clone repository

### ISSUE THREAD

**Issue by yashanet** [pancakeswap/token-list#73]
Issue when cloning repository https://github.com/pancakeswap/token-list.git : 
error: invalid path 'lists/images/aptos/0x881ac202b1f1e6ad4efcff7a1d0579411533f2502417a19211cfc49751ddb5f4::coin::MOJO.png'

Win 10.
git version 2.24.1.windows.2

**Comment by chef-jojo** [comment]
ah should be a file name issue on windows `:`

**Comment by chef-jojo** [comment]
I don't use windows myself. here you can find some tricks to get around. I didn't notice that it's going to be an issue for windows
https://stackoverflow.com/questions/5991805/how-do-i-clone-files-with-colons-in-the-filename

**Comment by yashanet** [comment]
Thanks a lot. And sorry I should research this issue myself.
